export const bookTitles = [
  "To Kill a Mockingbird",
  "1984",
  "The Great Gatsby",
  "Pride and Prejudice",
  "The Catcher in the Rye",
  "Harry Potter and the Sorcerer's Stone",
  "The Hobbit",
  "The Lord of the Rings",
  "The Chronicles of Narnia",
  "Jane Eyre",
  "Moby-Dick",
  "The Odyssey",
  "Brave New World",
  "The Grapes of Wrath",
  "The Picture of Dorian Gray",
  "Animal Farm",
  "The Adventures of Huckleberry Finn",
  "War and Peace",
  "The Little Prince",
  "Fahrenheit 451",
  "Frankenstein",
  "Alice's Adventures in Wonderland",
  "The Count of Monte Cristo",
  "Gone with the Wind",
  "Wuthering Heights",
  "The Scarlet Letter",
  "Dracula",
  "Don Quixote",
  "A Tale of Two Cities",
  "Les Misérables",
  "Anna Karenina",
  "The Bell Jar",
  "Lord of the Flies",
  "The Secret Garden",
  "Little Women",
  "The Alchemist",
  "The Stranger",
  "Slaughterhouse-Five",
  "One Hundred Years of Solitude",
  "The Road",
  "Catch-22",
  "The Stand",
  "The Hitchhiker's Guide to the Galaxy",
  "The Shining",
  "The Brothers Karamazov",
  "Crime and Punishment",
  "The Book Thief",
  "A Game of Thrones",
  "The Da Vinci Code",
  "The Hunger Games",
];
